### ISSUE TITLE
Autoplay Doesn't Autoplay Videos

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [Novicell/novicell-overlay#11]
it looks like the autoplay feature doesn't work:

```
document.addEventListener("DOMContentLoaded", function () {

    // Video overlay
    var videoOverlayTriggers = document.querySelectorAll('.js--video-modal');

    for (var i = 0; i < videoOverlayTriggers.length; i++) {
      videoOverlayTriggers[i].addEventListener('click', function(e){
        e.preventDefault();

        var currentTrigger = e.target;

        novicell.overlay.create({
          'isVideo': true,
          'videoId': currentTrigger.getAttribute('data-video-id'),
          'type': currentTrigger.getAttribute('data-type'),
          'class': 'video-overlay',
          'autoplay': 0
        });
      });
    }
  });
```

I've tried both `autoplay: 0` and `autoplay: 1`. I can work around this but thought I'd let you know.

Great modal overall though. Thanks for building this!

**Comment by thisislawatts** [comment]
Hey @DynamiteGoesBoom did you get to the bottom of this issue? I have pulled the repo and running locally with the latest version of Chrome I can see that the autoplay is working automatically for both the Youtube and Vimeo demos.

**Comment by DynamiteGoesBoom** [comment]
@thisislawatts I don't believe this is an issue anymore. Feel free to close this issue and thank you for taking the time to look into it!

**Comment by thisislawatts** [comment]
👍  Thanks for confirming @DynamiteGoesBoom. I'm not a maintainer on the project but was considering it for my own use with `autoplay` and wanted to check I wasn't missing anything.
